name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # You can specify the branch here (e.g., `main` or `develop`)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (used to build images for different architectures)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set the AWS region explicitly in the environment variables
    - name: Set AWS Region
      run: echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO_URL }} .
        docker tag ${{ secrets.ECR_REPO_URL }}:latest ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}

    # Push the Docker image to ECR
    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URL }}:latest
        docker push ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}
