name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Test AWS credentials
      run: |
        aws sts get-caller-identity --query Arn  # Check if AWS credentials work

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ECR_REPO_URL }} .
        docker tag ${{ secrets.ECR_REPO_URL }}:latest ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URL }}:latest
        docker push ${{ secrets.ECR_REPO_URL }}:${{ github.sha }}
